// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekcik.Entities;

#nullable disable

namespace Projekcik.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20251102202650_AddMigrations")]
    partial class AddMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekcik.Entities.Categories", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategorii"));

                    b.Property<string>("NazwaKategorii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategorii");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("Projekcik.Entities.Robots", b =>
                {
                    b.Property<int>("IdRobota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRobota"));

                    b.Property<int>("IdKategorii")
                        .HasColumnType("int");

                    b.Property<string>("NazwaRobota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRobota");

                    b.ToTable("Roboty");
                });

            modelBuilder.Entity("Projekcik.Entities.Team", b =>
                {
                    b.Property<int>("IdDruzyny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDruzyny"));

                    b.Property<int>("IdRobota")
                        .HasColumnType("int");

                    b.Property<int>("IdZawodnika")
                        .HasColumnType("int");

                    b.Property<string>("NazwaDruzyny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDruzyny");

                    b.ToTable("Druzyny");
                });

            modelBuilder.Entity("Projekcik.Entities.Users", b =>
                {
                    b.Property<int>("IdZawodnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZawodnika"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RozmiarKoszulki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("IdZawodnika");

                    b.ToTable("Zadownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
