// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekcik.Infrastructure.Persistance;

#nullable disable

namespace Projekcik.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20251104113054_relacje")]
    partial class relacje
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekcik.Entities.Categories", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategorii"));

                    b.Property<string>("NazwaKategorii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategorii");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("Projekcik.Entities.Robots", b =>
                {
                    b.Property<int>("IdRobota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRobota"));

                    b.Property<int>("CategoriesIdKategorii")
                        .HasColumnType("int");

                    b.Property<int>("IdDruzyny")
                        .HasColumnType("int");

                    b.Property<int>("IdKategorii")
                        .HasColumnType("int");

                    b.Property<string>("NazwaRobota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamIdDruzyny")
                        .HasColumnType("int");

                    b.HasKey("IdRobota");

                    b.HasIndex("CategoriesIdKategorii");

                    b.HasIndex("TeamIdDruzyny");

                    b.ToTable("Roboty");
                });

            modelBuilder.Entity("Projekcik.Entities.Team", b =>
                {
                    b.Property<int>("IdDruzyny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDruzyny"));

                    b.Property<int>("IdRobota")
                        .HasColumnType("int");

                    b.Property<string>("NazwaDruzyny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDruzyny");

                    b.ToTable("Druzyny");
                });

            modelBuilder.Entity("Projekcik.Entities.Users", b =>
                {
                    b.Property<int>("IdZawodnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZawodnika"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RozmiarKoszulki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("IdZawodnika");

                    b.ToTable("Zawodnicy");
                });

            modelBuilder.Entity("TeamUsers", b =>
                {
                    b.Property<int>("DruzynyIdDruzyny")
                        .HasColumnType("int");

                    b.Property<int>("ZawodnicyIdZawodnika")
                        .HasColumnType("int");

                    b.HasKey("DruzynyIdDruzyny", "ZawodnicyIdZawodnika");

                    b.HasIndex("ZawodnicyIdZawodnika");

                    b.ToTable("TeamUsers");
                });

            modelBuilder.Entity("Projekcik.Entities.Robots", b =>
                {
                    b.HasOne("Projekcik.Entities.Categories", "Categories")
                        .WithMany("Roboty")
                        .HasForeignKey("CategoriesIdKategorii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekcik.Entities.Team", "Team")
                        .WithMany("Roboty")
                        .HasForeignKey("TeamIdDruzyny")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamUsers", b =>
                {
                    b.HasOne("Projekcik.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("DruzynyIdDruzyny")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekcik.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("ZawodnicyIdZawodnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projekcik.Entities.Categories", b =>
                {
                    b.Navigation("Roboty");
                });

            modelBuilder.Entity("Projekcik.Entities.Team", b =>
                {
                    b.Navigation("Roboty");
                });
#pragma warning restore 612, 618
        }
    }
}
